@startuml
'https://plantuml.com/sequence-diagram

class App {
    + main()
    + start()
}

class ToDoList {
    + isCompleted: BooleanProperty
    + taskTitle: String
    + taskDescription: dueDate

    + ToDoList(taskTitle, taskDescription, dueDate, isCompleted): initializes the variables in ToDoList
    + completedProperty(): returns if the property is completed (booleanProperty)
    + isCompleted(): returns if the property is completed (boolean)
    + setIsCompleted(value): sets if the task is completed
    + getTaskTitle(): gets the task title
    + setTaskTitle(taskTitle): sets the task title
    + getTaskDescription(): gets the task taskDescription
    + setTaskDescription(taskDescription): sets the task description
    + getDueDate(): gets the due date
    + setDueDate(dueDate): sets the due date
}

class ToDoListController {
    + helpButton: Button - FXML
    + fileMenuButton: MenuButton - FXML
    + saveItemsButton: MenuItem - FXML
    + loadItemsButton: MenuItem - FXML
    + sortMenuButton: MenuButton - FXML
    + viewAllTasksButton: MenuItem - FXML
    + viewCompleteTasksButton: MenuItem - FXML
    + viewIncompleteTasksButton: MenuItem - FXML
    + taskTable: TableView<ToDoList> - FXML
    + markCompletedColumn: TableColumn<ToDoList, Boolean> - FXML
    + taskTitleColumn: TableColumn<ToDoList, String> - FXML
    + descriptionColumn: TableColumn<ToDoList, String> - FXML
    + dueDateColumn: TableColumn<ToDoList, String> - FXML
    + addTaskButton: Button - FXML
    + deleteTaskButton: Button - FXML
    + taskTitleTextField: TextField - FXML
    + taskDescriptionTextField: TextField - FXML
    + dueDatePicker: DatePicker - FXML

    + fileChooser: FileChooser
    + toDoItems: ObservableList<ToDoList>
    + filteredList: ObservableList<ToDoList>

    + quickSortButtonPressed(): Sorts by ascending due date
    + sort(ObservableList<ToDoList>): Sorts an observable list
    + addTaskButtonPressed(): add new item to existing to do list
    + addItems(String, String, String, Boolean): Adds items to the ObservableList of items
    + toInvalidDescriptionController(): Switches scene to InvalidDateController.fxml and returns a string
    + checkDescriptionLength(int): Returns true if the description is between 1 and 256 characters
    + clearTextFields(): Clears all the fields in the GUI
    + catchNullPointerDueDate(): Returns the value of the date picker. Returns " " if the date picker was null
    + dueDatePicked(): Returns the chosen due date
    + toInvalidDateController(): Switches scene to InvalidDateController.fxml and returns a string
    + deleteTaskButtonPressed(): returns true if the item was successfully removed
    + deleteAllItems(ToDoList): Resets all items of to do list to null and returns the empty object
    + deleteTask(ToDoList, ObservableList<ToDoList>): Removes task from ObservableList
    + clearListButtonPressed(): ObservableList is cleared
    + clearEntireList(ObservableList<ToDoList>): Returns and clears an ObservableList
    + helpButtonPressed(): Switches scene to the help controller
    + toHelpController(): Switches scene to the help controller
    + fileMenuButtonClicked(): Signifies that the file menu was opened
    + loadItemsButtonPressed(): Opens file chooser to load items
    + loadFileStrings(File): Returns an ArrayList of strings found in the file
    + addToObservableList(ArrayList<String>): Parses the strings in the ArrayList and returns them as an ObservableList
    + isBooleanPropertyTrue(String): Checks if the Boolean property is true or false
    + parseStrings(String): Parses the items
    + saveItemsButtonPressed(): save all items in a single to do list to external storage
    + saveList(File, ObservableList<ToDoList>): Writes the object to the file
    + sortMenuButtonClicked(): Signifies that the sort menu was clicked
    + viewAllTasksButtonPressed()): display all existing items
    + getAllTasks(ObservableList<ToDoList>): Returns a list with all of the items in it
    + filterList(ObservableList<ToDoList>)): Returns an ObservableList with items that were marked complete
    + isChecked(ToDoList): Returns state of check box
    + viewIncompleteTasksButtonPressed(): GUI displays only incompleted items
    + viewCompleteTasksButtonPressed(): GUI displays only complete items
    + filterIncompleteList(ObservableList<ToDoList>)): Adds only incomplete items the filtered list
    + initialize(): GUI components initialized and table set
}

class HelpController {
    + returnButton: Button - FXML
    + nextButton: Button - FXML

    + nextButtonPressed(): Scene is switched to next help screen
    + returnButtonPressed(): Scene is switched back to ToDoListController
    + initialize(): Initializes GUI components
}

class HelpDeleteTasksController {
    + returnButton: Button - FXML
    + nextButton: Button - FXML
    + backButton: Button - FXML

    + backButtonPressed(): Scene is switched to previous help screen
    + nextButtonPressed(): Scene is switched to next help scene
    + returnButtonPressed(): Scene is switched back to ToDoListController
    + initialize(): GUI components initialized
}

class HelpModifyTasksController {
    + returnButton: Button - FXML
    + nextButton: Button - FXML
    + backButton: Button - FXML

    + backButtonPressed(): Scene is switched to previous help screen
    + nextButtonPressed(): Scene is switched to next help scene
    + returnButtonPressed(): Scene is switched back to ToDoListController
    + initialize(): GUI components initialized
}

class HelpSaveLoadTasksController {
    + returnButton: Button - FXML
    + nextButton: Button - FXML
    + backButton: Button - FXML

    + backButtonPressed(): Scene is switched to previous help screen
    + nextButtonPressed(): Scene is switched to next help scene
    + returnButtonPressed(): Scene is switched back to ToDoListController
    + initialize(): GUI components initialized
}

class HelpSortTasksController {
    + returnButton: Button - FXML
    + backButton: Button - FXML

    + backButtonPressed(): Scene is switched to previous help screen
    + returnButtonPressed(): Scene is switched back to ToDoListController
    + initialize(): GUI components initialized
}

class InvalidDateController {
    + okButton: Button - FXML

    + okButtonPressed(): Scene is switched to ToDoList controller
    + initialize(): GUI components initialized
}

class InvalidDescriptionLengthController {
    + okButton: Button - FXML

    + okButtonPressed(): Scene switches to ToDoList Controller
    + initialize(): GUI components initialized
}

javafx.Application <|- App
App *--> ToDoListController
ToDoListController -- HelpController
ToDoListController -- InvalidDateController
ToDoListController -- InvalidDescriptionLengthController
HelpController -- HelpDeleteTasksController
HelpDeleteTasksController -- HelpModifyTasksController
HelpModifyTasksController -- HelpSaveLoadTasksController
HelpSaveLoadTasksController -- HelpSortTasksController
HelpSortTasksController -- HelpController
App *--> ToDoList
ToDoList - ToDoListController
@enduml