@startuml
'https://plantuml.com/sequence-diagram

class App {
    + main()
    + start()
}

class ToDoList {
    // Each to do list should be able to hold a table of tasks
    - toDoTitle: string
    - tasks: ArrayList<>

    + addTask(): adds task to arrayList
    + deleteTask(): removes task from arrayList
    + displayTasks()
    + updateToDoTitle(): user can rename list

}

class Task {
    completed: boolean
    taskTitle: string
    taskDescription: string
    date: datePicker?

    + updateDate()
    + updateDescription()
    + updateTitle()
    + isCompleted()

    + toString(): see if this will be necessary
}

class ToDoListController {
    + addTaskButtonPressed(ActionEvent): add new item to existing to do list
    + toTaskController(): Switches scene to TaskController.fxml and returns a string
    + deleteTaskButtonPressed(ActionEvent): remove item from existing to do list

    + fileMenuButtonClicked(ActionEvent):

    // THIS WILL NEED TO LOAD TO DO LIST NOT ITEMS
    + loadItemsButtonPressed(ActionEvent):

    + saveItemsButtonPressed(ActionEvent): save all items in a single to do list to external storage
    + sortMenuButtonClicked(ActionEvent)):
           + viewAllTasksButtonPressed(ActionEvent)): display all existing items
           + viewIncompleteTasksButtonPressed(ActionEvent)): display only the incompleted items
           + viewCompleteTasksButtonPressed(ActionEvent): display completed items
    + titleTextFieldClicked(ActionEvent)): edit the title of existing to do list
    + sortByDateButtonClicked(ActionEvent): sort items by due date
    + initialize():

    + taskCompletedCheckBoxClicked(): mark an item in a to do list as complete

}

class TaskController {
    + addItemButtonPressed(ActionEvent): adds item to ToDoList and switches screen
    - closeWithAddItemButton(): closes the TaskController.fxml scene when the addItemButton is successfully pressed
    + taskDescriptionFieldFilled(ActionEvent): edit description of an item within an existing to do list
    + dueDateCalendarFieldFilled(ActionEvent): edit the due date of an item within an existing to do list
    + returnToToDOListButtonPressed(ActionEvent): switches screen to To-Do List
    - closeWithReturnToToDoListButton(): closes the TaskController.fxml scene when the returnToToDoListButton is successfully pressed
    + titleTextFieldFilled((ActionEvent): add title to item in to do list
}




javafx.Application <|- App
App *--> ToDoListController
App *--> ToDoList
ToDoListController *--> TaskController
ToDoList *--> Task
ToDoList - ToDoListController
Task - TaskController

@enduml